use_frameworks!

platform :ios, '9.0'

target 'ModuleActionsCategorys_Example' do
  pod 'ModuleActionsCategorys', :path => '../'
#  pod 'CTMediator', :git => 'git@github.com:samingzhong/CTMediator.git'
#  pod 'SettingVC', :git => 'git@github.com:samingzhong/SettingVC.git', :commit => '8daa0b4fda33e284acfce6b6a622338eaf7d4005'
#  pod 'HomeVC', :git => 'git@github.com:samingzhong/HomeVC.git', :commit => '55adc85706785fed2ed0c8c7c09cec11f2ab3370'


pod 'CTMediator', :path => '../../CTMediator'
pod 'SettingVC', :path => '../../SettingVC'
pod 'HomeVC', :path => '../../HomeVC'


  target 'ModuleActionsCategorys_Tests' do
    inherit! :search_paths

    
  end
end
