use_frameworks!

platform :ios, '9.0'

target 'ModuleActionsCategorys_Example' do
  pod 'ModuleActionsCategorys', :path => '../'

  target 'ModuleActionsCategorys_Tests' do
    inherit! :search_paths

    
  end
end
